services:
  unifi-protect:
    image: dciancu/unifi-protect-unvr-docker-arm64:stable
    tty: true
    hostname: UNVR
    extra_hosts:
      - "UNVR:127.0.1.1"
    container_name: unifi-protect
    stop_grace_period: 2m
    cgroup: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - ./storage/srv:/srv
      - ./storage/data:/data
      - ./storage/persistent:/persistent
    environment:
      - container=docker
      - STORAGE_DISK=/dev/sda
      - TZ=UTC
      - DEBUG=false
    restart: unless-stopped
    cap_add:
      - dac_read_search
      - sys_admin
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/run
      - /var/run/lock
    privileged: true
    network_mode: host
