version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: arm.large
    working_directory: /mnt/ramdisk
    environment:
      BUILDKIT_PROGRESS: plain
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: firmware-{{ .Branch }}-{{ checksum "build-firmware.sh" }}-{{ checksum "firmware.Dockerfile" }}-
      - run:
          name: Build Firmware
          command: ./build-firmware.sh
      - save_cache:
          key: firmware-{{ .Branch }}-{{ checksum "build-firmware.sh" }}-{{ checksum "firmware.Dockerfile" }}-{{ checksum "firmware/version" }}
          paths:
            - firmware
      - run:
          name: Build Protect
          command: ./build-protect.sh
      - run:
          name: Publish Images
          command: ./publish.sh
      - run:
          name: Prune Docker Images
          command: docker image prune -f
